# Generated by Django 4.2.6 on 2023-10-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
